#' Show a palette
#'
#' Display a single palette to see whether it meets your needs.
#' If no \code{num} parameter is given,
#' all the colors in the palette will be displayed.
#' If \code{num} is less than the number of colors in the palette,
#' then only the first \code{num} colors will be displayed.
#' If \code{num} is greater than the number of colors in the palette,
#' then that many colors will be generated by linear interpolation
#' over the vector of colors in the chosen palette.
#' @param pal character, vector of (hexadecimal) colors representing a palette
#' @param ttl character, title to be displayed (the name of the palette)
#' @param num numeric, the number of colors to display
#' @examples
#' viz_palette(mn_palettes$accent)
#' viz_palette(mn_palettes$accent, "accent: first 4", num = 4)
#' viz_palette(mn_palettes$accent, "accent: interpolated to 25", num = 25)
#'
#' @export
#' @importFrom graphics image
#' @importFrom grDevices colorRampPalette
#'
viz_palette <- function(pal, 
                        ttl = deparse(substitute(pal)),
                        num = length(pal)) {
    if(num <= 0)
        stop("'num' should be > 0")
    pal_func <- colorRampPalette(pal)
    image(seq_len(num), 1, as.matrix(seq_len(num)), col = pal_func(num),
          main = paste0(ttl, " (", length(pal), " colours in palette, ", num, " displayed)"),
          xlab = "", ylab = "", xaxt = "n", yaxt = "n",  bty = "n")
}
